annotated stuff
lblod/editor-templates pull request #5
Opened 2022-03-09 15:43 UTC by Asergey91

2022-03-18 07:47 UTC, nvdk approved these changes
looks good!

2022-03-18 07:47 UTC, nvdk commented
@Asergey91 did you also create a migration for this in app-gelinkt-notuleren?

2022-04-06 20:35 UTC, abeforgit requested changes

2022-04-06 20:35 UTC, abeforgit commented on standaard-templates/besluit/nieuw/aanvullend-reglement-besluit.ttl
> +     <li>code van de wegbeheerder - <a class=\"annotation\" href=\"https://codex.vlaanderen.be/doc/document/1035575\" property=\"eli.cites\" typeof=\"eli:LegalExpression\">ministerieel besluit van 11
please pay attention to correct rdfa syntax
I see it's also wrong in the line above
```suggestion
     <li>code van de wegbeheerder - <a class=\"annotation\" href=\"https://codex.vlaanderen.be/doc/document/1035575\" property=\"eli:cites\" typeof=\"eli:LegalExpression\">ministerieel besluit van 11 oktober 1976 houdende de minimumafmetingen en de bijzondere plaatsingsvoorwaarden van de verkeerstekens</a></li>
```

2022-04-06 20:40 UTC, abeforgit requested changes

2022-04-06 20:40 UTC, abeforgit commented on standaard-templates/besluit/nieuw/aanvullend-reglement-besluit.ttl
>       <li>wegcode - Koninklijk Besluit <a class=\"annotation\" href=\"https://codex.vlaanderen.be/doc/document/1036242\" property=\"eli.cites\" typeof=\"eli:LegalExpression\">van 1 december 1975 houde
```suggestion
     <li>wegcode - Koninklijk Besluit <a class=\"annotation\" href=\"https://codex.vlaanderen.be/doc/document/1036242\" property=\"eli:cites\" typeof=\"eli:LegalExpression\">van 1 december 1975 houdende algemeen reglement op de politie van het wegverkeer en van het gebruik van de openbare weg.</a></li>
```

2022-04-07 16:10 UTC, abeforgit commented
The citation on line 41 is also not correctly annotated. Technically not in scope of this pr, but might as well fix it while we're at it

2022-05-03 11:31 UTC, merged